# Numpy practice session

In [1]:
# import this library in jupyter notebook
import numpy as np

# Creating an array using numpy

In [2]:
# 1-D array
food=np.array(["pakora", "samosa", "raita"])
food

array(['pakora', 'samosa', 'raita'], dtype='<U6')

In [3]:
price=np.array([5,5,5])
price

array([5, 5, 5])

In [4]:
type(price)


numpy.ndarray

In [5]:
type(food)

numpy.ndarray

In [6]:
len(food)

3

In [7]:
price[2]

5

In [8]:
price[0:]

array([5, 5, 5])

In [9]:
food[0]

'pakora'

In [10]:
price.mean()

5.0

In [11]:
# zeros method
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
# ones
np.ones(4)

array([1., 1., 1., 1.])

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
#specify range
np.arange(2,25)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24])

In [15]:
# specify range with interval
np.arange(10,30,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [16]:
# table of 5
np.arange(5,55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [17]:
#line space
np.linspace(0,10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [18]:
# specify data type
np.ones(5, dtype=np.int64)

array([1, 1, 1, 1, 1], dtype=int64)

In [19]:
np.ones(5, dtype=np.float64)

array([1., 1., 1., 1., 1.])

# Array Functions

In [20]:
a=np.array([10,12,15,2,4,6,100,320,0.5,10.3])
a

array([ 10. ,  12. ,  15. ,   2. ,   4. ,   6. , 100. , 320. ,   0.5,
        10.3])

In [21]:
a.sort()
a

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ])

In [22]:
b=np.array([10.2,3.4,53.6,91.6, 45.5])
b

array([10.2,  3.4, 53.6, 91.6, 45.5])

In [23]:
# concatenation
c = np.concatenate((a,b))
c

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ,  10.2,   3.4,  53.6,  91.6,  45.5])

In [24]:
c.sort()
c

array([  0.5,   2. ,   3.4,   4. ,   6. ,  10. ,  10.2,  10.3,  12. ,
        15. ,  45.5,  53.6,  91.6, 100. , 320. ])

# 2-D Arrays

In [32]:
x=np.array([[1,2,],[3,4]])
x



array([[1, 2],
       [3, 4]])

In [33]:
y= np.array([[6,7], [8,9]])
y

array([[6, 7],
       [8, 9]])

In [34]:
np.concatenate((x,y), axis=0)

array([[1, 2],
       [3, 4],
       [6, 7],
       [8, 9]])

In [36]:
np.concatenate((x,y), axis=1)

array([[1, 2, 6, 7],
       [3, 4, 8, 9]])

In [37]:
a = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
a

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [38]:
# to find the number of dimensions
a.ndim

3

In [39]:
b=np.array([[5,6,7],
           [8,9,10],
           [10,11,12]])
b


array([[ 5,  6,  7],
       [ 8,  9, 10],
       [10, 11, 12]])

In [40]:
b.ndim

2

In [41]:
# size (no: of elements)
a.size

24

In [43]:
a

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [42]:
a.shape

(3, 2, 4)

In [46]:
a=np.arange(9) #3*#
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [47]:
#reshape
a=a.reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [48]:
#reshape
np.reshape(a, newshape=(1,9), order='C')

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

# convert 1-D into 2-D

In [50]:
a= np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
a.shape # 1-D array

(9,)

In [52]:
# row-wise conversion
b=a[np.newaxis, :]
b


array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [53]:
b.shape # 2D array

(1, 9)

In [54]:
# column wise conversion
c=a[:, np.newaxis]
c


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [55]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
# slicing
a[2:6]

array([3, 4, 5, 6])

In [57]:
a*6

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54])

In [58]:
a+6

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

In [59]:
a.sum()

45

In [60]:
a.mean()

5.0